### PR TITLE
Update ext_localconf.php

### PR DESCRIPTION
**Pull request by ghost**
Use Typo3 DriverRegistry instead the $GLOBALS['TYPO3_CONF_VARS']['SYS']['fal']['registeredDrivers'] old way.

I have to make this change in a Typo3 8.7.19 installation to see the sftp driver.

I don't find when exactly the old way was disabled and maybe it's better to add a conditional version if the DriverRegistry is newer than Typo3 7.6.
But assuming the api documentation, replacement is ok.
https://api.typo3.org/typo3cms/7/html/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_resource_1_1_driver_1_1_driver_registry.html

### CODE REVIEW

**Comment by vertexvaar** [comment]
Hi @stephane-wecker 

digging into this issue i found that registering the driver via `$GLOBALS` still works in 9.5 LTS. It seems that nothing has changed regarding.
Your problem may arise because of the driver registry betimes. When it's constructed once it will read the array and write them to an internal property. Since it's a singleton registering other drivers is not possible anymore using the array. Please check if the `DriverRegistry` is used before EXT:falsftp could register itself using the array.

Anyway: I'll ask in the TYPO3 core dev channel if the DriverRegistry should be used (despite it's bad design considering the complications) and will merge your request accordingly ;)

**Comment by ghost** [comment]
Hi @vertexvaar,
Yes, the instance of Typo3 use the `aus_driver_amazon_s3 `extention and this extention use the `DriverRegistry`.
As I understand, it will be an issue each time Typo3 use `$GLOBALS` and `DriverRegistry `method. Maybe this point have to be fixed in Typo3 core ?

**Comment by vertexvaar** [comment]
Hi @stephane-wecker 

so i got the [answer from the TYPO3 coredev channel](https://typo3.slack.com/archives/C03AM9R17/p1538658116000100) which boils down to:
> Use `$GLOBALS['TYPO3_CONF_VARS']['SYS']['fal']['registeredDrivers']`
> `DriverRegistry::registerDriverClass()` is prohibited there.

Considering this i will decline your pull request, because this extension is doing it right.
Thank you anyway for your efforts.

Regarding your issue: You should be fine copying the entry from the ext_localconf to your LocalConfiguration.php ord AdditionalConfiguration.php. That way the driver will be registered before the AWS fal driver comes along.

**Comment by ghost** [comment]
I saw your pull request for the other extension.
Thanks for that job :-)

For information : https://github.com/andersundsehr/aus_driver_amazon_s3/pull/41

**Pull request closed without merging**
